In [3]:
#GROUPING AND AGGREGATION
# To compare subsets
# To deduce reasons why subgroup differ
# To subset your data for your analysis
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [14]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/mtcars.csv'
cars = pd.read_csv(url, header=0)

# Rename all 14 columns
cars.columns = ['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb', 'fast', 'cars', 'car_names']

cars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,fast,cars,car_names
0,4.582576,6,160.0,110,3.90,2.620,16.46,0,1,4,4,1,Mazda RX4,Mazda RX4
1,4.582576,6,160.0,110,3.90,2.875,17.02,0,1,4,4,1,Mazda RX4 Wag,Mazda RX4 Wag
2,4.774935,4,108.0,93,3.85,2.320,18.61,1,1,4,1,1,Datsun 710,Datsun 710
3,4.626013,6,258.0,110,3.08,3.215,19.44,1,0,3,1,1,Hornet 4 Drive,Hornet 4 Drive
4,4.324350,8,360.0,175,3.15,3.440,17.02,0,0,3,2,1,Hornet Sportabout,Hornet Sportabout

In [15]:
cars_groups = cars.groupby(cars['cyl'])
cars_groups.mean(numeric_only=True)

,mpg,disp,hp,drat,wt,qsec,vs,am,gear,carb,fast
cyl,,,,,,,,,,,
4,5.147091,105.136364,82.636364,4.070909,2.285727,19.137273,0.909091,0.727273,4.090909,1.545455,1.000000
6,4.440690,183.314286,122.285714,3.585714,3.117143,17.977143,0.571429,0.428571,3.857143,3.428571,1.000000
8,3.872129,353.100000,209.214286,3.229286,3.999214,16.772143,0.000000,0.142857,3.285714,3.500000,0.285714